#include "lpc_puf.h"
#include <stdlib.h>
#include "fsl_device_registers.h"
//#include "fsl_debug_console.h"
//#include "board.h"

#include "fsl_puf.h"

#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_power.h"

/* User key in little-endian format. */
/* 32 bytes key for ECB method: "Thispasswordisveryuncommonforher". */
static const uint8_t s_userKey256[] __attribute__((aligned)) = {
    0x72, 0x65, 0x68, 0x72, 0x6f, 0x66, 0x6e, 0x6f, 0x6d, 0x6d, 0x6f, 0x63, 0x6e, 0x75, 0x79, 0x72,
    0x65, 0x76, 0x73, 0x69, 0x64, 0x72, 0x6f, 0x77, 0x73, 0x73, 0x61, 0x70, 0x73, 0x69, 0x68, 0x54};

void lpc_puf_init()
{
    status_t result;
    uint8_t activationCode[PUF_ACTIVATION_CODE_SIZE];
    uint8_t keyCode0[PUF_GET_KEY_CODE_SIZE_FOR_KEY_SIZE(32)];
    uint8_t keyCode1[PUF_GET_KEY_CODE_SIZE_FOR_KEY_SIZE(PUF_INTRINSIC_KEY_SIZE)];
    uint8_t intrinsicKey[16] = {0};

    POWER_SetBodVbatLevel(kPOWER_BodVbatLevel1650mv, kPOWER_BodHystLevel50mv, false);

    srand(0xbabadeda);
    printf("PUF Peripheral Driver Example\r\n\r\n");

    puf_config_t conf;
    PUF_GetDefaultConfig(&conf);

    /* Initialize PUF peripheral */
    result = PUF_Init(PUF, &conf);
    if (result != kStatus_Success)
    {
        printf("Error Initializing PUF!\r\n");
    }

    // /* Perform enroll to get device specific PUF activation code */
    // /* Note: Enroll operation is usually performed only once for each device. */
    // /* Activation code is stored and used in Start operation */
    // result = PUF_Enroll(PUF, activationCode, sizeof(activationCode));
    // if (result == kStatus_EnrollNotAllowed)
    // {
    //     printf("Enroll is not allowed!\r\n");
    //     printf("Will make powercycle and enroll again!\r\n");
    //     (void)PUF_PowerCycle(PUF, &conf);
    //     result = PUF_Enroll(PUF, activationCode, sizeof(activationCode));
    // }

    // if (result != kStatus_Success)
    // {
    //     printf("Error during Enroll!\r\n");
    // }
    // PUF_Deinit(PUF, &conf);

    // /* Reinitialize PUF after enroll */
    // result = PUF_Init(PUF, &conf);
    // if (result != kStatus_Success)
    // {
    //     printf("Error Initializing PUF!\r\n");
    // }

    // /* Start PUF by loading generated activation code */
    // result = PUF_Start(PUF, activationCode, sizeof(activationCode));
    // if (result == kStatus_StartNotAllowed)
    // {
    //     printf("Start is not allowed!\r\n");
    //     printf("Will make powercycle and start again!\r\n");
    //     (void)PUF_PowerCycle(PUF, &conf);
    //     result = PUF_Start(PUF, activationCode, sizeof(activationCode));
    // }

    // if (result != kStatus_Success)
    // {
    //     printf("Error during Start !\r\n");
    // }

    // /* Create keycode for user key with index 0 */
    // /* Index 0 selects that the key shall be ouptut (by PUF_GetHwKey()) to a SoC specific private hardware bus. */
    // result = PUF_SetUserKey(PUF, kPUF_KeyIndex_00, s_userKey256, 32, keyCode0, sizeof(keyCode0));
    // if (result != kStatus_Success)
    // {
    //     printf("Error setting user key!\r\n");
    // }

    // /* Generate new intrinsic key with index 1 */
    // result = PUF_SetIntrinsicKey(PUF, kPUF_KeyIndex_01, PUF_INTRINSIC_KEY_SIZE, keyCode1, sizeof(keyCode1));
    // if (result != kStatus_Success)
    // {
    //     printf("Error setting intrinsic key!\r\n");
    // }

    // /* Reconstruct key from keyCode0 to HW bus for crypto module */
    // result = PUF_GetHwKey(PUF, keyCode0, sizeof(keyCode0), kPUF_KeySlot0, rand());
    // if (result != kStatus_Success)
    // {
    //     printf("Error reconstructing key to HW bus!\r\n");
    // }

    // /* Reconstruct intrinsic key from keyCode1 generated by PUF_SetIntrinsicKey() */
    // result = PUF_GetKey(PUF, keyCode1, sizeof(keyCode1), intrinsicKey, sizeof(intrinsicKey));
    // if (result != kStatus_Success)
    // {
    //     printf("Error reconstructing intrinsic key!\r\n");
    // }

    // printf("Reconstructed intrinsic key = ");
    // for (int i = 0; i < 16; i++)
    // {
    //     printf("%x ", intrinsicKey[i]);
    // }


    return;
}
